/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package StudentPackage;

import java.util.ArrayList;


/**
 *
 * @author Normie
 */
public class GUI_Update extends javax.swing.JFrame {

    Process_Student ps = new Process_Student();
    public GUI_Update() {
        initComponents();
        jLB_Result.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTX_ID = new javax.swing.JTextField();
        jTX_Name = new javax.swing.JTextField();
        jTX_Mark = new javax.swing.JTextField();
        jCB_ClassID = new javax.swing.JComboBox<>();
        jRB_Male = new javax.swing.JRadioButton();
        jRB_Female = new javax.swing.JRadioButton();
        jBT_finding = new javax.swing.JButton();
        jBT_update = new javax.swing.JButton();
        jLB_Result = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cập nhật thông tin sinh viên");

        jLabel1.setText("Mã sinh viên");

        jLabel2.setText("Họ tên ");

        jLabel3.setText("Lớp");

        jLabel4.setText("Giới tính");

        jLabel5.setText("Điểm");

        jCB_ClassID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "61TH1", "61TH2", "61TH3", "61TH4", "61TH5", "61TH6" }));

        jRB_Male.setText("Nam");
        jRB_Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_MaleActionPerformed(evt);
            }
        });

        jRB_Female.setText("Nữ");
        jRB_Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRB_FemaleActionPerformed(evt);
            }
        });

        jBT_finding.setText("Tìm kiếm");
        jBT_finding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_findingActionPerformed(evt);
            }
        });

        jBT_update.setText("Cập nhật");
        jBT_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT_updateActionPerformed(evt);
            }
        });

        jLB_Result.setText("Hiển thị");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCB_ClassID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRB_Male)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRB_Female))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTX_Name))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTX_Mark)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBT_update))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel1)
                                .addGap(15, 15, 15)
                                .addComponent(jTX_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBT_finding))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLB_Result, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTX_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBT_finding))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTX_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jCB_ClassID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jRB_Male)
                            .addComponent(jRB_Female)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jBT_update)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTX_Mark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLB_Result)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBT_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_updateActionPerformed
        // TODO add your handling code here:
        String ID = jTX_ID.getText();
        String Name = jTX_Name.getText();
        String ClassID = jCB_ClassID.getSelectedItem().toString();
        boolean Gender = true;
        if (jRB_Male.isSelected()) {
            Gender = true;
        }
        if (jRB_Female.isSelected()) {
            Gender = false;
        }
        double Mark = Double.parseDouble(jTX_Mark.getText());
        
        if(ps.updateStudent(ID, Name, ClassID, Gender, Mark)){
            jLB_Result.setText("Cập nhật thành công");
        
        }
        else{
            jLB_Result.setText("Cập nhật không thành công");
        }
        jLB_Result.setVisible(true);
    }//GEN-LAST:event_jBT_updateActionPerformed

    private void jBT_findingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT_findingActionPerformed
        // TODO add your handling code here:
         ArrayList<Student> lst = ps.getStudent_byID(jTX_ID.getText().toString());
         for (int i = 0; i < lst.size(); i++) {
            Student s = (Student)lst.get(i);
            jTX_ID.setText(s.getID());
            jCB_ClassID.setSelectedItem(s.getClass().toString());
            jTX_Name.setText(s.getName());
            jTX_Mark.setText(Double.toString(s.getMark()));
            if(s.isGender()){
                jRB_Male.setSelected(true);
                jRB_Female.setSelected(false);
            }
            else{
                jRB_Male.setSelected(false);
                jRB_Female.setSelected(true);
            }
        }
    }//GEN-LAST:event_jBT_findingActionPerformed

    private void jRB_MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_MaleActionPerformed
        // TODO add your handling code here:
         jRB_Female.setSelected(false);
    }//GEN-LAST:event_jRB_MaleActionPerformed

    private void jRB_FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRB_FemaleActionPerformed
        // TODO add your handling code here:
        jRB_Male.setSelected(false);
    }//GEN-LAST:event_jRB_FemaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBT_finding;
    private javax.swing.JButton jBT_update;
    private javax.swing.JComboBox<String> jCB_ClassID;
    private javax.swing.JLabel jLB_Result;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton jRB_Female;
    private javax.swing.JRadioButton jRB_Male;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTX_ID;
    private javax.swing.JTextField jTX_Mark;
    private javax.swing.JTextField jTX_Name;
    // End of variables declaration//GEN-END:variables
}
